[package]
name = "log_work"
version = "0.1.0"
authors = ["belgoking <belgoking@gmx.de>"]
edition = "2018"

[dependencies]
regex = "0.2"
lazy_static = "1.4.0"
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.2"
app_dirs = "1.2"
